aa_graphSampleSizeSummary_overTime <-
function(FILEPATH,MEASURES,MAXSAMPLESIZE,SMALL,MEDIUM,LARGE,SUMMARYFILENAME,TIMEPOINTS,TIMEPOINTSCALE)
{
	# GRAPH FOR EACH TIMEPOINT
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		ATESTSUMMARYFILE <- paste(SUMMARYFILENAME,"_",TIMEPOINTANALYSED,sep="")
		GRAPHOUTPUTFILE <- paste("ATestMaxes_",TIMEPOINTANALYSED,sep="")

		aa_graphSampleSizeSummary(FILEPATH,MEASURES,MAXSAMPLESIZE,SMALL,MEDIUM,LARGE,ATESTSUMMARYFILE,GRAPHOUTPUTFILE,TIMEPOINTANALYSED,TIMEPOINTSCALE)
	}
}

