efast_generate_medians_for_all_parameter_subsets <-
function(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,OUTPUTCOLSTART,OUTPUTCOLEND,RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME)
{
	for(CURVE in 1:NUMCURVES)				# REPRESENTS THE CURVES
	{
		# NOW LOOK AT EACH PARAMETER OF INTEREST
		for(PARAM in 1:length(PARAMETERS))
		{
			print(paste("Curve: ",CURVE," Param: ",PARAM,sep=""))

			# NOW LOOK AT EACH OF THE RUNS FOR THIS PARAMETER SET
			for(j in 1:NUMSAMPLES)
			{
				SAMPLEFILEDIR<-paste(FILEPATH,"/",CURVE,"/",PARAM,"/",j,"/",sep="")

				if(!file.exists(paste(SAMPLEFILEDIR,MEDIANSFILENAME,sep="")))
				{
					getMediansSubset(SAMPLEFILEDIR,NUMRUNSPERSAMPLE,OUTPUTCOLSTART,OUTPUTCOLEND,MEASURES,RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME)
					
				}

		
			}
		}
	}
}

