efast_get_overall_medians_overTime <-
function(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,CURVERESULTSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTPROCESSING<-TIMEPOINTS[n]

		print(paste("Time Point Processing: ",TIMEPOINTPROCESSING,sep=""))
		MEDIANSFILENAMEFULL <- paste(MEDIANSFILENAME,"_",TIMEPOINTPROCESSING,sep="")
		CURVERESULTSFILENAMEFULL<-paste(CURVERESULTSFILENAME,"_",TIMEPOINTPROCESSING,sep="")

		efast_get_overall_medians(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL,CURVERESULTSFILENAMEFULL)
	}
}

