efast_generate_medians_for_all_parameter_subsets_overTime <-
function(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,RESULTFILEFORMAT,RESULTFILENAME,ALTERNATIVEFILENAME,
		OUTPUTCOLSTART,OUTPUTCOLEND,MEDIANSFILEFORMAT,MEDIANSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTPROCESSING<-TIMEPOINTS[n]
		print(paste("Timepoint: ",TIMEPOINTPROCESSING,sep=""))

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTPROCESSING,sep="")
		SIMRESULTFILENAME<-paste(RESULTFILENAME,"_",TIMEPOINTPROCESSING,sep="")
		
		if(!is.null(ALTERNATIVEFILENAME))
		{
			ALTERNATIVEFILENAMEFULL<-paste(ALTERNATIVEFILENAME,"_",TIMEPOINTPROCESSING,sep="")
			efast_generate_medians_for_all_parameter_subsets(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,
					RESULTFILEFORMAT,SIMRESULTFILENAME,ALTERNATIVEFILENAMEFULL,OUTPUTCOLSTART,OUTPUTCOLEND,MEDIANSFILEFORMAT,
					MEDIANSFILENAMEFULL)
		}
		else
		{
			efast_generate_medians_for_all_parameter_subsets(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,
					RESULTFILEFORMAT,SIMRESULTFILENAME,ALTERNATIVEFILENAME,OUTPUTCOLSTART,OUTPUTCOLEND,MEDIANSFILEFORMAT,
					MEDIANSFILENAMEFULL)
		}

		

	}
}

