efast_run_Analysis_overTime <-
function(FILEPATH,MEASURES,PARAMETERS,NUMCURVES,NUMSAMPLES,CURVERESULTSFILENAME,EFASTRESULTFILENAME,OUTPUTMEASURES_TO_TTEST,TTEST_CONF_INT,GRAPH_FLAG,TIMEPOINTS,TIMEPOINTSCALE)
{
	# NOW PROCESS THE DATA FROM EACH CAPTURED TIMEPOINT
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]
		print(TIMEPOINTANALYSED)
	
		CURVERESULTSFILENAMEFULL<-paste(CURVERESULTSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		EFASTRESULTFILENAMEFULL<-paste(EFASTRESULTFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")

		efast_run_Analysis(FILEPATH,MEASURES,PARAMETERS,NUMCURVES,NUMSAMPLES,OUTPUTMEASURES_TO_TTEST,
			TTEST_CONF_INT,GRAPH_FLAG,CURVERESULTSFILENAMEFULL,EFASTRESULTFILENAMEFULL,TIMEPOINTANALYSED,TIMEPOINTSCALE)
	}
}

