efast_get_overall_medians_overTime <-
function(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILENAME,CURVERESULTSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTPROCESSING<-TIMEPOINTS[n]
		MEDIANSFILENAMEFULL <- paste(MEDIANSFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		CURVERESULTSFILENAMEFULL<-paste(CURVERESULTSFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")

		efast_get_overall_medians(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILENAMEFULL,CURVERESULTSFILENAMEFULL)
	
	}
}

