efast_generate_medians_for_all_parameter_subsets_overTime <-
function(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,OUTPUTCOLSTART,OUTPUTCOLEND,RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTPROCESSING<-TIMEPOINTS[n]
		print(paste("Timepoint: ",TIMEPOINTPROCESSING,sep=""))

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		SIMRESULTFILENAME<-paste(RESULTFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		
		if(!is.null(ALTERNATIVEFILENAME))
		{
			ALTERNATIVEFILENAME<-paste(ALTERNATIVEFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		}

		efast_generate_medians_for_all_parameter_subsets(FILEPATH,NUMCURVES,PARAMETERS,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,OUTPUTCOLSTART,OUTPUTCOLEND,SIMRESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAMEFULL)

	}
}

