lhc_generatePRCoEffs_overTime <-
function(FILEPATH,PARAMETERS,MEASURES,LHCSUMMARYFILENAME,CORCOEFFSOUTPUTFILE,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		LHCRESULTFILE<-paste(LHCSUMMARYFILENAME,"_",TIMEPOINTANALYSED,sep="")
		CORCOEFFSOUTPUTFILEFULL<-paste(CORCOEFFSOUTPUTFILE,"_",TIMEPOINTANALYSED,sep="")

		lhc_generatePRCoEffs(FILEPATH,PARAMETERS,MEASURES,LHCRESULTFILE,CORCOEFFSOUTPUTFILEFULL)
	}
}

