lhc_generate_netlogo_LHCSummary <- function(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,LHCSUMMARYFILENAME)
{
	# Check the parameter and measures strings
	PARAMETERS<-table_header_check(PARAMETERS)
	MEASURES<-table_header_check(MEASURES)

	# Call the spartan function
	lhc_generateLHCSummary(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,
			MEDIANSFILENAME,LHCSUMMARYFILENAME)
}
