lhc_generateLHCSummary_overTime <-
function(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,LHCSUMMARYFILENAME,TIMEPOINTS)
{	
	# NOW PROCESS EACH TIME POINT
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]
		print(paste("Processing Time Point ",TIMEPOINTANALYSED,sep=""))

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,sep="")
		LHCSUMMARYFILENAMEFULL<-paste(LHCSUMMARYFILENAME,"_",TIMEPOINTANALYSED,sep="")

		lhc_generateLHCSummary(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL,LHCSUMMARYFILENAMEFULL)
	}
}

