lhc_process_sample_run_subsets <-
function(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,OUTPUTCOLSTART,OUTPUTCOLEND,MEASURES,RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME)
{
	for(k in 1:NUMSAMPLES)
	{
		print(k)
		MEDIANFILEPATH<-paste(FILEPATH,"/",k,"/",sep="")
		
		# CHECK WHETHER THIS HAS ALREADY BEEN DONE (SAVES TIME IN ERROR CIRCUMSTANCES)
		MEDIANRESULTSFILE = paste(MEDIANFILEPATH,"/",MEDIANSFILENAME,sep="")

		if(!file.exists(MEDIANRESULTSFILE))
		{
			getMediansSubset(MEDIANFILEPATH,NUMRUNSPERSAMPLE,OUTPUTCOLSTART,OUTPUTCOLEND,MEASURES,
				RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME)
		}
		
	}
}

