lhc_process_sample_run_subsets_overTime <-
function(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,RESULTFILEFORMAT,RESULTFILENAME,ALTERNATIVEFILENAME,OUTPUTCOLSTART,OUTPUTCOLEND,MEDIANSFILEFORMAT,
		MEDIANSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,sep="")
		SIMRESULTFILENAME<-paste(RESULTFILENAME,"_",TIMEPOINTANALYSED,sep="")

		if(!is.null(ALTERNATIVEFILENAME))
		{
			ALTERNATIVEFILENAMEFULL<-paste(ALTERNATIVEFILENAME,"_",TIMEPOINTANALYSED,sep="")
			
			lhc_process_sample_run_subsets(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,RESULTFILEFORMAT,SIMRESULTFILENAME,ALTERNATIVEFILENAMEFULL,OUTPUTCOLSTART,
					OUTPUTCOLEND,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL)
		}
		else
		{
			lhc_process_sample_run_subsets(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,MEASURES,RESULTFILEFORMAT,SIMRESULTFILENAME,ALTERNATIVEFILENAME,OUTPUTCOLSTART,
					OUTPUTCOLEND,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL)
		}

		
	}
}

