lhc_process_sample_run_subsets_overTime <-
function(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,OUTPUTCOLSTART,OUTPUTCOLEND,MEASURES,RESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME,TIMEPOINTS)
{
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		SIMRESULTFILENAME<-paste(RESULTFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")

		if(!is.null(ALTERNATIVEFILENAME))
		{
			ALTERNATIVEFILENAME<-paste(ALTERNATIVEFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		}

		lhc_process_sample_run_subsets(FILEPATH,NUMSAMPLES,NUMRUNSPERSAMPLE,OUTPUTCOLSTART,OUTPUTCOLEND,MEASURES,SIMRESULTFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAMEFULL)

	}
}

