lhc_generateLHCSummary_overTime <-
function(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILENAME,LHCSUMMARYFILENAME,TIMEPOINTS)
{	
	# NOW PROCESS EACH TIME POINT
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		LHCSUMMARYFILENAMEFULL<-paste(LHCSUMMARYFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")

		lhc_generateLHCSummary(FILEPATH,LHC_PARAM_CSV_LOCATION,PARAMETERS,NUMSAMPLES,MEASURES,MEDIANSFILENAMEFULL,LHCSUMMARYFILENAMEFULL)
	}
}

