oat_netlogo_graphATestsForSampleSize<-function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEASURES,ATESTSIGLEVEL,ATESTRESULTSFILENAME,TIMEPOINTS,TIMEPOINTSCALE)
{
	# Check the parameter and measures strings
	PARAMETERS<-table_header_check(PARAMETERS)
	MEASURES<-table_header_check(MEASURES)

	# Call the spartan function
	oat_graphATestsForSampleSize(FILEPATH,PARAMETERS,PMIN,
		PMAX,PINC,MEASURES,ATESTSIGLEVEL,
		ATESTRESULTSFILENAME,TIMEPOINTS,TIMEPOINTSCALE)

}
