oat_netlogo_analyseAllParams<-function(FILEPATH,PARAMETERS,BASELINE,PMIN,PMAX,PINC,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,ATESTRESULTSFILENAME)
{
	# Check the parameter and measures strings
	PARAMETERS<-table_header_check(PARAMETERS)
	MEASURES<-table_header_check(MEASURES)

	# Call the spartan function
	oat_analyseAllParams(FILEPATH,PARAMETERS,BASELINE,PMIN,
		PMAX,PINC,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,
		ATESTRESULTSFILENAME)
}
