oat_graphATestsForSampleSize_overTime <-
function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,ATESTRESULTSFILENAME,MEASURES,ATESTSIGLEVEL,TIMEPOINTS,TIMEPOINTSCALE)
{
	# LOOK AT EACH TIMEPOINT FOR THIS PARAMETER
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		ATESTSFILENAME <- paste(ATESTRESULTSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		
		oat_graphATestsForSampleSize(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEASURES,ATESTSIGLEVEL,ATESTSFILENAME,TIMEPOINTANALYSED,TIMEPOINTSCALE)
	}
}

