oat_netlogo_plotResultDistribution<-function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEASURES,MEASURE_SCALE,MEDIANSFILEFORMAT,MEDIANSFILENAME,TIMEPOINTS,TIMEPOINTSCALE)
{
	# Check the parameter and measures strings
	PARAMETERS<-table_header_check(PARAMETERS)
	MEASURES<-table_header_check(MEASURES)

	# Call the spartan function
	oat_plotResultDistribution(FILEPATH,PARAMETERS,PMIN,
		PMAX,PINC,MEASURES,MEASURE_SCALE,MEDIANSFILEFORMAT,
		MEDIANSFILENAME,TIMEPOINTS,TIMEPOINTSCALE)


}
