oat_plotResultDistribution_overTime <-
function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEDIANSFILENAME,MEASURES,MEASURE_SCALE,TIMEPOINTS,TIMEPOINTSCALE)
{
	# NOW LOOK AT ALL CAPTURED TIMEPOINTS FOR THIS PARAMETER
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")

		oat_plotResultDistribution(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEASURES,MEASURE_SCALE,MEDIANSFILENAMEFULL,TIMEPOINTANALYSED,TIMEPOINTSCALE)
		

	}
}

