oat_processParamSubsets_overTime <-
function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,NUMRUNSPERSAMPLE,MEASURES,OUTPUTCOLSTART,OUTPUTCOLEND,RESULTSFILENAME,ALTERNATIVEFILENAME,MEDIANSFILENAME,TIMEPOINTS)
{
	# CREATE THE MEDIAN DISTRIBUTION OVER THE SET OF RUNS FOR EACH PARAMETER SET, FOR EACH PARAMETER (AS THIS IS ONE AT A TIME)
	# LIKE ALL THE OTHER FUNCTIONS, USES MEDIANFUNCTIONS.R TO CREATE THIS

	# NOW CREATE THE MEDIANS FOR EACH OF THE TIMEPOINTS FOR THIS VALUE
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTPROCESSING<-TIMEPOINTS[n]
		print(paste("TIMEPOINT: ",TIMEPOINTPROCESSING,sep=""))

		SIMRESULTFILENAME<-paste(RESULTSFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		print(SIMRESULTFILENAME)
		
		if(!is.null(ALTERNATIVEFILENAME))
		{
			ALTERNATIVEFILENAMEFULL<-paste(ALTERNATIVEFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")
		}
		else
		{
			ALTERNATIVEFILENAMEFULL<-ALTERNATIVEFILENAME
		}

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTPROCESSING,".csv",sep="")

		oat_processParamSubsets(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,NUMRUNSPERSAMPLE,MEASURES,OUTPUTCOLSTART,OUTPUTCOLEND,
			SIMRESULTFILENAME,ALTERNATIVEFILENAMEFULL,MEDIANSFILENAMEFULL)
	}
}

