oat_plotResultDistribution_overTime <-
function(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEDIANSFILEFORMAT,MEDIANSFILENAME,MEASURES,MEASURE_SCALE,TIMEPOINTS,TIMEPOINTSCALE)
{
	# NOW LOOK AT ALL CAPTURED TIMEPOINTS FOR THIS PARAMETER
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,sep="")

		oat_plotResultDistribution(FILEPATH,PARAMETERS,PMIN,PMAX,PINC,MEASURES,MEASURE_SCALE,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL,
				TIMEPOINTANALYSED,TIMEPOINTSCALE)
		

	}
}

