oat_analyseAllParams_overTime <-
function(FILEPATH,PARAMETERS,BASELINE,PMIN,PMAX,PINC,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAME,ATESTRESULTSFILENAME,TIMEPOINTS)
{
	# CONSIDER EACH TIMEPOINT FOR THIS PARAMETER
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,sep="")
		ATESTRESULTSFILENAMEFULL<-paste(ATESTRESULTSFILENAME,"_",TIMEPOINTANALYSED,sep="")

		oat_analyseAllParams(FILEPATH,PARAMETERS,BASELINE,PMIN,PMAX,PINC,MEASURES,MEDIANSFILEFORMAT,MEDIANSFILENAMEFULL,ATESTRESULTSFILENAMEFULL)
	}
}

