oat_analyseAllParams_overTime <-
function(FILEPATH,PARAMETERS,BASELINE,PMIN,PMAX,PINC,MEASURES,MEDIANSFILENAME,ATESTRESULTSFILENAME,TIMEPOINTS)
{
	# CONSIDER EACH TIMEPOINT FOR THIS PARAMETER
	for(n in 1:length(TIMEPOINTS))
	{
		TIMEPOINTANALYSED<-TIMEPOINTS[n]

		MEDIANSFILENAMEFULL<-paste(MEDIANSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")
		ATESTRESULTSFILENAMEFULL<-paste(ATESTRESULTSFILENAME,"_",TIMEPOINTANALYSED,".csv",sep="")

		oat_analyseAllParams(FILEPATH,PARAMETERS,BASELINE,PMIN,PMAX,PINC,MEASURES,MEDIANSFILENAMEFULL,ATESTRESULTSFILENAMEFULL)
	}
}

